// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Article_Author;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Article_ArticleType

typedef GPB_ENUM(Article_ArticleType) {
  Article_ArticleType_Novel = 0,
  Article_ArticleType_Prose = 1,
  Article_ArticleType_Paper = 2,
  Article_ArticleType_Poetry = 3,
};

GPBEnumDescriptor *Article_ArticleType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Article_ArticleType_IsValidValue(int32_t value);

#pragma mark - PersonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PersonRoot : GPBRootObject
@end

@interface PersonRoot (DynamicMethods)
+ (GPBExtensionDescriptor *)followersCount;
+ (GPBExtensionDescriptor *)likesCount;
@end

#pragma mark - Article

typedef GPB_ENUM(Article_FieldNumber) {
  Article_FieldNumber_ArticleId = 1,
  Article_FieldNumber_ArticleExcerpt = 2,
  Article_FieldNumber_ArticlePictureArray = 3,
  Article_FieldNumber_ArticlePagecount = 4,
  Article_FieldNumber_ArticleType = 5,
  Article_FieldNumber_Author = 6,
  Article_FieldNumber_ArticleNumberofwordsArray = 7,
};

@interface Article : GPBMessage

@property(nonatomic, readwrite) int32_t articleId;

@property(nonatomic, readwrite) BOOL hasArticleId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *articleExcerpt;
/** Test to see if @c articleExcerpt has been set. */
@property(nonatomic, readwrite) BOOL hasArticleExcerpt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *articlePictureArray;
/** The number of items in @c articlePictureArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger articlePictureArray_Count;

@property(nonatomic, readwrite) int32_t articlePagecount;

@property(nonatomic, readwrite) BOOL hasArticlePagecount;
@property(nonatomic, readwrite) Article_ArticleType articleType;

@property(nonatomic, readwrite) BOOL hasArticleType;
@property(nonatomic, readwrite, strong, null_resettable) Article_Author *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *articleNumberofwordsArray;
/** The number of items in @c articleNumberofwordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger articleNumberofwordsArray_Count;

@end

#pragma mark - Article_Author

typedef GPB_ENUM(Article_Author_FieldNumber) {
  Article_Author_FieldNumber_Name = 1,
  Article_Author_FieldNumber_Phone = 2,
};

@interface Article_Author : GPBMessage

/** 作者的名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;
/** Test to see if @c phone has been set. */
@property(nonatomic, readwrite) BOOL hasPhone;

@end

#pragma mark - Other

typedef GPB_ENUM(Other_FieldNumber) {
  Other_FieldNumber_OtherInfo = 1,
  Other_FieldNumber_Code1 = 2,
  Other_FieldNumber_Code2 = 3,
};

typedef GPB_ENUM(Other_TestOneof_OneOfCase) {
  Other_TestOneof_OneOfCase_GPBUnsetOneOfCase = 0,
  Other_TestOneof_OneOfCase_Code1 = 2,
  Other_TestOneof_OneOfCase_Code2 = 3,
};

@interface Other : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *otherInfo;
/** Test to see if @c otherInfo has been set. */
@property(nonatomic, readwrite) BOOL hasOtherInfo;

@property(nonatomic, readonly) Other_TestOneof_OneOfCase testOneofOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code2;

@end

/**
 * Clears whatever value was set for the oneof 'testOneof'.
 **/
void Other_ClearTestOneofOneOfCase(Other *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
